#012 Feat: Create Footer Section
apeunit/even-music pull request #13
Opened 2023-01-24 18:01 UTC by Fidesnoella

# PR
## PR Description
Create footer section.
## Task ID and Ticket Card Link
Task ID: # 012
Ticket Card Link: [here](https://www.notion.so/apeunit/Footer-section-bdeb5f617ed24e6cb1d3ff2b43ba4350)
## Completed Tasks
- [x] create footer component
- [x] add footer component to homepage
## Testing
- npm install
- npm run dev
- view homepage

2023-01-24 18:30 UTC, izzett222 requested changes
on tablet the footer section is not divided into four equal parts, some part are bigger than the other in the design

2023-01-24 18:45 UTC, izzett222 requested changes

2023-01-24 18:45 UTC, izzett222 commented on tailwind.config.js
> +        1.25: "5.3125rem", //85px
1.25 doesn't follow the convention of dividing the px value by four

2023-01-24 18:45 UTC, izzett222 commented on components/layout/Footer.jsx
> +                <span className=""><Anchor url={"mailto:even@apeunit.com"}>Get In Touch</Anchor></span>
Could you remove the empty className string?

2023-01-24 18:45 UTC, izzett222 commented on components/layout/Footer.jsx
> +            <div className="sm:border-l-0.5 border-black pl-0 sm:pl-5 pb-5 sm:pb-10  pr-4 sm:pr-2.5 pt-5 sm:pt-0.75 xl:pt-0">
There is an extra space in the className. Could you remove it.

2023-01-24 18:45 UTC, izzett222 commented on components/layout/Footer.jsx
> +            <div className="pb-0 sm:pb-10 pt-0.5 sm:pt-0.75 xl:pt-0 sm:pr-2 pr-5  xl:pl-10.5">
There is an extra space in the className. Could you remove it?

2023-01-24 18:45 UTC, izzett222 commented on components/layout/Footer.jsx
> +            <div className="border-l-0.5 border-black pb-0 sm:pb-10 pt-1 sm:pt-0.75 xl:pt-0 pr-2.5 xl:pr-21.25 pl-5 sm:pl-2.5 xl:pl-5 ">
There is an extra space in the className at the end. Could you remove it.

2023-01-24 18:45 UTC, izzett222 commented on components/layout/Footer.jsx
> +                <h5 className="font-variation-secondary block font-semibold sm:text-sm text-xs -tracking-tight leading-3.75 sm:leading-4.25 text-black">Even</h5>
h5 tag is a block by default so the block is not needed.

2023-01-24 18:45 UTC, izzett222 commented on components/layout/Footer.jsx
> +                <h5 className="font-variation-secondary block font-semibold sm:text-sm text-xs -tracking-tight leading-3.75 sm:leading-4.25 text-black">Miguel Lizio</h5>
h5 tag is a block by default so the block is not needed.

2023-01-25 09:45 UTC, izzett222 approved these changes

2023-01-25 09:49 UTC, Nkaka23dev approved these changes

2023-01-25 09:49 UTC, merged